### ISSUE TITLE
FP16

### ISSUE THREAD

**Issue by TillBeemelmanns** [scepter914/DepthAnything-ROS#2]
Hi,

cool package which works for us. Something that confused me was the following line in the README.md

>  DepthAnything-ROS supports in "fp32" for now.

Actually we tested FP16 and it works fine without any changes to the code, you just have to wait 4-5 minutes on the first start up.

Bests,
Till

**Comment by scepter914** [comment]
@TillBeemelmanns 

Thank you for reporting so kindly.
I fixed README in [this PR](https://github.com/scepter914/DepthAnything-ROS/pull/3) from your report.

(By the way I recently wonder for robust 3D detection in worse condition like snow and losing sensor data, and I can find your work [MultiCorrupt](https://github.com/ika-rwth-aachen/MultiCorrupt) from your github.
It is a good experience for me as advantage of OSS development. Thank you.)
