### ISSUE TITLE
Metric depth estimation or relative depth estimation？

### ISSUE THREAD

**Issue by Redreadblack** [scepter914/DepthAnything-ROS#4]
After watching the video, I want to know whether the output depth imgae result is metric depth or relative depth? 
If it is metric depth, how is it obtained? 
Thank you

**Comment by scepter914** [comment]
Thank you for opening issue.
This package uses relative depth only.
For your information, [the conversation of this issues](https://github.com/scepter914/DepthAnything-ROS/issues/1) can help you.

**Comment by scepter914** [comment]
@Redreadblack 

Thank you for opening issue.
This package uses relative depth only.
For your information, [the conversation of this issues](https://github.com/scepter914/DepthAnything-ROS/issues/1) can help you.

**Comment by Redreadblack** [comment]
ths for your reply, this is what I want
