### ISSUE TITLE
How did you fine-tune DA models to  nuscenes

### ISSUE THREAD

**Issue by I3aer** [scepter914/DepthAnything-ROS#5]
Hi,

Are you using a metric model or relative model? If you use a metric model, can you tell me how to fine-tune it to nsucenes images?

Thank you,

**Comment by scepter914** [comment]
This package uses relative depth only.
For your information, [the conversation of this issues](https://github.com/scepter914/DepthAnything-ROS/issues/1) can help you.

**Comment by scepter914** [comment]
@I3aer 
Friendly ping, and I close this issue.
