### ISSUE TITLE
How to compile a usable ONNX model based on VITS

### ISSUE THREAD

**Issue by Fusica** [scepter914/DepthAnything-ROS#6]

**Comment by scepter914** [comment]
I don't understand what you mean.
Clarify more about the background and problem (If there is no response for a week, the issue will be closed.)

**Comment by Fusica** [comment]
I'm very sorry I didn't provide more details. In the README on setting the onnx file, you mentioned "If you want to make onnx files yourself, please use [depth-anything-tensorrt](https://github.com/spacewalk01/depth-anything-tensorrt/issues/10)." However, this link has expired. When I wanted to deploy this code to my edge device (Jetson Orin NX), I found that it seems to crash directly due to CPU overload at runtime because the default onnx file used is based on vitb. Therefore, I want to use a smaller depth anything model based on vits, but I don't know how to generate an onnx model suitable for this project. Please advise!

**Comment by scepter914** [comment]
I understand your problem.
I cannot why https://github.com/spacewalk01/depth-anything-tensorrt/issues/10 is deleted, but if you follow "Model Preparation Depth-Anything-V1" in the README of https://github.com/spacewalk01/depth-anything-tensorrt, then you may make onnx files.

Anyway, fortunately I find the onnx file in my PC, so would you download the onnx file by following command?

```
gdown 1Qr2xjiaPvPD8j4aXwsnVJokoWgLHiTEr
```

**Comment by Fusica** [comment]
Thank you very much! Using the onnx you provided, I successfully ran depth anything on nx at a frequency of 9hz.
